export const COPY_STRUCTURE:'COPY_STRUCTURE' = 'COPY_STRUCTURE';
export const CUT_STRUCTURE:'CUT_STRUCTURE' = 'CUT_STRUCTURE';
export const RENAME_STRUCTURE:'RENAME_STRUCTURE' = 'RENAME_STRUCTURE';
export const DELETE_STRUCTURE:'DELETE_STRUCTURE' = 'DELETE_STRUCTURE';