export const OPEN_WINDOW:'OPEN_WINDOW' = 'OPEN_WINDOW';
export const RESIZE_WINDOW:'RESIZE_WINDOW' = 'RESIZE_WINDOW';
export const REPOSITION_WINDOW:'REPOSITION_WINDOW' = 'REPOSITION_WINDOW';
export const TO_ACTIVE_WINDOW:'TO_ACTIVE_WINDOW' = 'TO_ACTIVE_WINDOW';
export const TO_DISACTIVE_WINDOWS:'TO_DISACTIVE_WINDOWS' = 'TO_DISACTIVE_WINDOWS';
export const TO_EXPAND_WINDOW:'TO_EXPAND_WINDOW' = 'TO_EXPAND_WINDOW';
export const CLOSE_WINDOW:'CLOSE_WINDOW' = 'CLOSE_WINDOW';